select 'AAABBCDDEEE' , 
INSTR('AAABBCDDEEE', 'A', -1, 1)||'A'||
INSTR(SUBSTR('AAABBCDDEEE', INSTR('AAABBCDDEEE', 'A', -1, 1)+1), 'B', -1, 1) ||'B' ||
INSTR(SUBSTR('AAABBCDDEEE', INSTR('AAABBCDDEEE', 'B', -1, 1)+1),'C', -1, 1 )||'C'||
INSTR(SUBSTR('AAABBCDDEEE', INSTR('AAABBCDDEEE', 'C', -1, 1)+1),'D', -1, 1)||'D'||
INSTR(SUBSTR('AAABBCDDEEE', INSTR('AAABBCDDEEE', 'D', -1, 1)+1), 'E', -1, 1)||'E' as CNT
from dual;

SELECT REGEXP_COUNT ('AAABBCDDEEEABBCCDEEEAA', 'A')||'A'||
REGEXP_COUNT ('AAABBCDDEEEABBCCDEEEAA', 'B')||'B'||
REGEXP_COUNT ('AAABBCDDEEEABBCCDEEEAA', 'C')||'C'||
REGEXP_COUNT ('AAABBCDDEEEABBCCDEEEAA', 'D')||'D'||
REGEXP_COUNT ('AAABBCDDEEEABBCCDEEEAA', 'E')||'E'
FROM dual;

